// <auto-generated />
namespace BookHospitalService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApplicationUserProfileComplete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplicationUserProfileComplete));
        
        string IMigrationMetadata.Id
        {
            get { return "201907112020377_ApplicationUser.ProfileComplete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
